### ISSUE TITLE
new CI fails

### ISSUE THREAD

**Issue by puririshi98** [pyg-team/pytorch_geometric#6782]
### 🐛 Describe the bug

```
=========================== short test summary info ============================
FAILED test/datasets/test_elliptic.py::test_elliptic_bitcoin_dataset - TypeEr...
FAILED test/utils/test_convert.py::test_to_cugraph[False-True-edge_weight1]
FAILED test/utils/test_convert.py::test_to_cugraph[False-False-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[True-True-None] - assert...
FAILED test/utils/test_convert.py::test_from_cugraph[True-True-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[True-False-None] - asser...
FAILED test/utils/test_convert.py::test_from_cugraph[True-False-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[False-True-None] - asser...
FAILED test/utils/test_convert.py::test_from_cugraph[False-True-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[False-False-None] - asse...
FAILED test/utils/test_convert.py::test_from_cugraph[False-False-edge_weight1]
FAILED test/utils/test_spmm.py::test_spmm_basic[device1] - AssertionError: as...
==== 12 failed
```

```
=================================== FAILURES ===================================
________________________ test_elliptic_bitcoin_dataset _________________________
get_dataset = functools.partial(<function load_dataset at 0x7f5c16405ee0>, '/tmp/pyg_test_datasets')
    @onlyFullTest
    def test_elliptic_bitcoin_dataset(get_dataset):
>       dataset = get_dataset(name='EllipticBitcoinDataset')
test/datasets/test_elliptic.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:41: in load_dataset
    return EllipticBitcoinDataset(path, *args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/datasets/elliptic.py:60: in __init__
    super().__init__(root, transform, pre_transform)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/in_memory_dataset.py:57: in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/dataset.py:97: in __init__
    self._process()
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/dataset.py:224: in _process
    self.process()
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/datasets/elliptic.py:90: in process
    x = torch.from_numpy(df_features.loc[:, 2:].values).to(torch.float)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:873: in __getitem__
    return self._getitem_tuple(key)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1055: in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:750: in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1088: in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1122: in _get_slice_axis
    indexer = labels.slice_indexer(
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:4966: in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5169: in slice_locs
    start_slice = self.get_slice_bound(start, "left", kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5079: in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5031: in _maybe_cast_slice_bound
    self._invalid_indexer("slice", label)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Index([     'txId', 'time_step',           2,           3,           4,
                 5,           6,           7, ...        161,
               162,         163,         164,         165,         166],
      dtype='object', length=167)
form = 'slice', key = 2
    def _invalid_indexer(self, form: str_t, key):
        """
        Consistent invalid indexer message.
        """
>       raise TypeError(
            f"cannot do {form} indexing on {type(self).__name__} with these "
            f"indexers [{key}] of type {type(key).__name__}"
        )
E       TypeError: cannot do slice indexing on Index with these indexers [2] of type int
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:3267: TypeError
___________________ test_to_cugraph[False-True-edge_weight1] ___________________
edge_weight = tensor([0.4664, 0.3317, 0.4964, 0.4277]), directed = False
relabel_nodes = True
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.rand(4)])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    @pytest.mark.parametrize('directed', [True, False])
    def test_to_cugraph(edge_weight, directed, relabel_nodes):
        import cugraph
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        graph = to_cugraph(edge_index, edge_weight, relabel_nodes, directed)
        assert isinstance(graph, cugraph.Graph)
        assert graph.number_of_nodes() == 3
    
        edge_list = graph.view_edge_list()
        assert edge_list is not None
    
        edge_list = edge_list.sort_values(by=['src', 'dst'])
    
        cu_edge_index = edge_list[['src', 'dst']].to_pandas().values
        assert edge_index.tolist() == cu_edge_index.T.tolist()
    
        if edge_weight is not None:
            cu_edge_weight = edge_list['weights'].to_pandas().values
>           assert edge_weight.tolist() == cu_edge_weight.tolist()
E           assert [0.4664377570...6652932167053] == [0.4664377570...7101001739502]
E             Left contains 2 more items, first extra item: 0.4963948[726](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/jobs/53984430#L726)654053
E             Use -v to get the full diff
test/utils/test_convert.py:433: AssertionError
__________________ test_to_cugraph[False-False-edge_weight1] ___________________
edge_weight = tensor([0.4664, 0.3317, 0.4964, 0.4277]), directed = False
relabel_nodes = False
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.rand(4)])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    @pytest.mark.parametrize('directed', [True, False])
    def test_to_cugraph(edge_weight, directed, relabel_nodes):
        import cugraph
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        graph = to_cugraph(edge_index, edge_weight, relabel_nodes, directed)
        assert isinstance(graph, cugraph.Graph)
        assert graph.number_of_nodes() == 3
    
        edge_list = graph.view_edge_list()
        assert edge_list is not None
    
        edge_list = edge_list.sort_values(by=['src', 'dst'])
    
        cu_edge_index = edge_list[['src', 'dst']].to_pandas().values
        assert edge_index.tolist() == cu_edge_index.T.tolist()
    
        if edge_weight is not None:
            cu_edge_weight = edge_list['weights'].to_pandas().values
>           assert edge_weight.tolist() == cu_edge_weight.tolist()
E           assert [0.4664377570...6652932167053] == [0.4664377570...7101001[739](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/jobs/53984430#L739)502]
E             Left contains 2 more items, first extra item: 0.4963948726654053
E             Use -v to get the full diff
test/utils/test_convert.py:433: AssertionError
______________________ test_from_cugraph[True-True-None] _______________________
edge_weight = None, directed = True, relabel_nodes = True
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0, 2, 1], [2, 1, 1, 0]] == [[0, 1, 1, 2], [1, 0, 2, 1]]
E         At index 0 diff: [1, 0, 2, 1] != [0, 1, 1, 2]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
__________________ test_from_cugraph[True-True-edge_weight1] ___________________
edge_weight = tensor([-0.2837,  0.9451, -0.3490,  0.4564]), directed = True
relabel_nodes = True
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0, 2, 1], [2, 1, 1, 0]] == [[0, 1, 1, 2], [1, 0, 2, 1]]
E         At index 0 diff: [1, 0, 2, 1] != [0, 1, 1, 2]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
______________________ test_from_cugraph[True-False-None] ______________________
edge_weight = None, directed = False, relabel_nodes = True
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0], [2, 1]] == [[0, 1], [1, 2]]
E         At index 0 diff: [1, 0] != [0, 1]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
__________________ test_from_cugraph[True-False-edge_weight1] __________________
edge_weight = tensor([-0.2837,  0.9451, -0.3490,  0.4564]), directed = False
relabel_nodes = True
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0], [2, 1]] == [[0, 1], [1, 2]]
E         At index 0 diff: [1, 0] != [0, 1]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
______________________ test_from_cugraph[False-True-None] ______________________
edge_weight = None, directed = True, relabel_nodes = False
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 1, 2, 0], [0, 2, 1, 1]] == [[0, 1, 1, 2], [1, 0, 2, 1]]
E         At index 0 diff: [1, 1, 2, 0] != [0, 1, 1, 2]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
__________________ test_from_cugraph[False-True-edge_weight1] __________________
edge_weight = tensor([-0.2837,  0.9451, -0.3490,  0.4564]), directed = True
relabel_nodes = False
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 1, 2, 0], [0, 2, 1, 1]] == [[0, 1, 1, 2], [1, 0, 2, 1]]
E         At index 0 diff: [1, 1, 2, 0] != [0, 1, 1, 2]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
_____________________ test_from_cugraph[False-False-None] ______________________
edge_weight = None, directed = False, relabel_nodes = False
    @withPackage('cudf')
/usr/local/lib/python3.8/dist-packages/coverage/control.py:836: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0], [2, 1]] == [[0, 1], [1, 2]]
E         At index 0 diff: [1, 0] != [0, 1]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
_________________ test_from_cugraph[False-False-edge_weight1] __________________
edge_weight = tensor([-0.2837,  0.9451, -0.3490,  0.4564]), directed = False
relabel_nodes = False
    @withPackage('cudf')
    @withPackage('cugraph')
    @pytest.mark.parametrize('edge_weight', [None, torch.randn(4)])
    @pytest.mark.parametrize('directed', [True, False])
    @pytest.mark.parametrize('relabel_nodes', [True, False])
    def test_from_cugraph(edge_weight, directed, relabel_nodes):
        import cudf
        import cugraph
        from torch.utils.dlpack import to_dlpack
    
        if directed:
            edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])
        else:
            edge_index = torch.tensor([[0, 1], [1, 2]])
    
        if edge_weight is not None:
            edge_weight[:edge_index.size(1)]
    
        G = cugraph.Graph(directed=directed)
        df = cudf.from_dlpack(to_dlpack(edge_index.t()))
        if edge_weight is not None:
            df['2'] = cudf.from_dlpack(to_dlpack(edge_weight))
    
        G.from_cudf_edgelist(
            df,
            source=0,
            destination=1,
            edge_attr='2' if edge_weight is not None else None,
            renumber=relabel_nodes,
        )
    
        cu_edge_index, cu_edge_weight = from_cugraph(G)
    
>       assert cu_edge_index.tolist() == edge_index.tolist()
E       assert [[1, 0], [2, 1]] == [[0, 1], [1, 2]]
E         At index 0 diff: [1, 0] != [0, 1]
E         Use -v to get the full diff
test/utils/test_convert.py:469: AssertionError
___________________________ test_spmm_basic[device1] ___________________________
device = device(type='cuda', index=0)
    @withCUDA
    def test_spmm_basic(device):
        src = torch.randn(5, 4, device=device)
        other = torch.randn(4, 8, device=device)
    
        out1 = src @ other
        out2 = spmm(src.to_sparse(), other, reduce='sum')
        out3 = spmm(SparseTensor.from_dense(src), other, reduce='sum')
        assert out1.size() == (5, 8)
>       assert torch.allclose(out1, out2)
E       AssertionError: assert False
E        +  where False = <built-in method allclose of type object at 0x7f5bcc3dcbc0>(tensor([[ 2.0477, -1.1278, -0.3330,  1.9007,  3.0619,  1.4840,  2.0230, -2.3307],\n        [ 1.2360,  2.8585, -1.6878, ...8,  1.4510],\n        [ 0.8829, -2.6074,  0.4[767](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/jobs/53984430#L767),  2.0739,  3.5401,  2.6623,  0.9645, -1.9539]],\n       device='cuda:0'), tensor([[ 2.0484, -1.1278, -0.3330,  1.9013,  3.0617,  1.4845,  2.0231, -2.3308],\n        [ 1.2361,  2.8589, -1.6877, ...8,  1.4507],\n        [ 0.8829, -2.6078,  0.4[768](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/jobs/53984430#L768),  2.0739,  3.5405,  2.6624,  0.9641, -1.[954](https://gitlab-master.nvidia.com/dl/dgx/pyg/-/jobs/53984430#L954)3]],\n       device='cuda:0'))
E        +    where <built-in method allclose of type object at 0x7f5bcc3dcbc0> = torch.allclose
test/utils/test_spmm.py:19: AssertionError
=============================== warnings summary ===============================
../../../usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/graphgym/config.py:19
  /usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/graphgym/config.py:19: UserWarning: Could not define global config object. Please install 'yacs' via 'pip install yacs' in order to use GraphGym
    warnings.warn("Could not define global config object. Please install "
../../../usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/graphgym/imports.py:14
  /usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/graphgym/imports.py:14: UserWarning: Please install 'pytorch_lightning' via  'pip install pytorch_lightning' in order to use GraphGym
    warnings.warn("Please install 'pytorch_lightning' via  "
../../../usr/local/lib/python3.8/dist-packages/optuna/storages/_rdb/models.py:35
  /usr/local/lib/python3.8/dist-packages/optuna/storages/_rdb/models.py:35: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    BaseModel: Any = declarative_base()
test/nn/conv/test_lg_conv.py::test_lg_conv
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1480: UserWarning: operator() profile_node %570 : int = prim::profile_ivalue(%565)
   does not have profile information (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:105.)
    return forward_call(*args, **kwargs)
test/nn/models/test_basic_gnn.py: 1 warning
test/nn/models/test_rev_gnn.py: 20 warnings
  /usr/local/lib/python3.8/dist-packages/torch/storage.py:315: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.
    warnings.warn(message, UserWarning)
-- Docs: https://docs.pytest.org/en/stable/warnings.html
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Coverage XML written to file coverage.xml
=========================== short test summary info ============================
FAILED test/datasets/test_elliptic.py::test_elliptic_bitcoin_dataset - TypeEr...
FAILED test/utils/test_convert.py::test_to_cugraph[False-True-edge_weight1]
FAILED test/utils/test_convert.py::test_to_cugraph[False-False-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[True-True-None] - assert...
FAILED test/utils/test_convert.py::test_from_cugraph[True-True-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[True-False-None] - asser...
FAILED test/utils/test_convert.py::test_from_cugraph[True-False-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[False-True-None] - asser...
FAILED test/utils/test_convert.py::test_from_cugraph[False-True-edge_weight1]
FAILED test/utils/test_convert.py::test_from_cugraph[False-False-None] - asse...
FAILED test/utils/test_convert.py::test_from_cugraph[False-False-edge_weight1]
FAILED test/utils/test_spmm.py::test_spmm_basic[device1] - AssertionError: as...
==== 12 failed, 3723 passed, 493 skipped, 25 warnings in 296.83s (0:04:56) =====
```

### Environment

updated to latest pyg and pyg-lib after the last issue was addressed

**Comment by puririshi98** [comment]
if the cugraph issues need to be dealt w/ by cugraph folks lmk

**Comment by rusty1s** [comment]
I fixed cugraph related tests in https://github.com/pyg-team/pytorch_geometric/pull/6788. Regarding `spmm` tests, I am not totally sure. Do you mind taking a look as well? It runs fine for me locally.

**Comment by puririshi98** [comment]
okay ill rerun CI w/ latest and if issue still persists Ill investigate myself

**Comment by puririshi98** [comment]
i updated the pyg and pyg-lib submodules but the issue still persists for all tests, ill have cugraph investigate and ill look into the spmm stuff

**Comment by puririshi98** [comment]
using our 23.02 container (which had previously gone through CI at the beginning of the month and was fine) the spmm test passes. however if i update to the latest master branch source build inside this container, I can repro the issue. I can repro it using our 23.02 container (cuda12) + master branch pyg as well as 22.12 container (cuda11) + master branch pyg

**Comment by puririshi98** [comment]
i further confirmed that i can repro the cugraph issues using the 23.02 cugraph/rapids tag

**Comment by puririshi98** [comment]
@rusty1s do uk whats causing this bitcoin test to fail? idk much about  the data or the test. if u cant repro or dont know whats up w/ it i can also look into it along w the spmm test.
```
________________________ test_elliptic_bitcoin_dataset _________________________
get_dataset = functools.partial(<function load_dataset at 0x7f5c16405ee0>, '/tmp/pyg_test_datasets')
    @onlyFullTest
    def test_elliptic_bitcoin_dataset(get_dataset):
>       dataset = get_dataset(name='EllipticBitcoinDataset')
test/datasets/test_elliptic.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/conftest.py:41: in load_dataset
    return EllipticBitcoinDataset(path, *args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/datasets/elliptic.py:60: in __init__
    super().__init__(root, transform, pre_transform)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/in_memory_dataset.py:57: in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/dataset.py:97: in __init__
    self._process()
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/dataset.py:224: in _process
    self.process()
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/datasets/elliptic.py:90: in process
    x = torch.from_numpy(df_features.loc[:, 2:].values).to(torch.float)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:873: in __getitem__
    return self._getitem_tuple(key)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1055: in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:750: in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1088: in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1122: in _get_slice_axis
    indexer = labels.slice_indexer(
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:4966: in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5169: in slice_locs
    start_slice = self.get_slice_bound(start, "left", kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5079: in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:5031: in _maybe_cast_slice_bound
    self._invalid_indexer("slice", label)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = Index([     'txId', 'time_step',           2,           3,           4,
                 5,           6,           7, ...        161,
               162,         163,         164,         165,         166],
      dtype='object', length=167)
form = 'slice', key = 2
    def _invalid_indexer(self, form: str_t, key):
        """
        Consistent invalid indexer message.
        """
>       raise TypeError(
            f"cannot do {form} indexing on {type(self).__name__} with these "
            f"indexers [{key}] of type {type(key).__name__}"
        )
E       TypeError: cannot do slice indexing on Index with these indexers [2] of type int
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:3267: TypeError
```

**Comment by puririshi98** [comment]
i also checked that the cugraph failure exists independently of the pandas version.
note:it fails regardless of what pandas version even though pandas is a requirement for the cugraph stuff since uninstalling pandas causes this failure:
```
____________________________________________________________________________________ ERROR collecting test/utils/test_convert.py _____________________________________________________________________________________
ImportError while importing test module '/opt/pyg/pytorch_geometric/test/utils/test_convert.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/opt/pyg/pytorch_geometric/test/utils/test_convert.py:404: in <module>
    ???
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/testing/decorators.py:90: in withPackage
    na_packages = set(package for package in args if not is_installed(package))
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/testing/decorators.py:90: in <genexpr>
    na_packages = set(package for package in args if not is_installed(package))
/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/testing/decorators.py:78: in is_installed
    module = import_module(req.name)
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/usr/local/lib/python3.8/dist-packages/cudf/__init__.py:12: in <module>
    from cudf import api, core, datasets, testing
/usr/local/lib/python3.8/dist-packages/cudf/api/__init__.py:3: in <module>
    from cudf.api import extensions, types
/usr/local/lib/python3.8/dist-packages/cudf/api/extensions/__init__.py:3: in <module>
    from cudf.api.extensions.accessor import (
/usr/local/lib/python3.8/dist-packages/cudf/api/extensions/accessor.py:5: in <module>
    from pandas.core.accessor import CachedAccessor
E   ModuleNotFoundError: No module named 'pandas'
```

**Comment by rusty1s** [comment]
Ok, In this case I think all we need to do is add `pandas>=1.5.2` to `setup.py`.

What is the latest error log on the cugraph tests? I assumed that just sorting the final edge indices resolves the issue, but haven't confirmed it is working since I have trouble installing it due to some `GLIBC` issues.

**Comment by puririshi98** [comment]
[full_23.03_CI_Error_log.txt](https://github.com/pyg-team/pytorch_geometric/files/10903350/full_23.03_CI_Error_log.txt)
tons of issues but they should be relatively simple to fix:
cugraph test just needs `to(device)` in most cases
cugraph ops models seem to have numerical mismatches which are quite small at first glance, could just increase tolerance
spmm has quite a variety of issues.
neighborloader issues look like the usage of neighborsampling changed but the loaders didnt get updated or something

**Comment by puririshi98** [comment]
@rusty1s confirming if this would be okay

**Comment by puririshi98** [comment]
> neighborloader issues look like the usage of neighborsampling changed but the loaders didnt get updated or something

actually its solved now, i guess we were just behind by a few commits
https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/sampler/neighbor_sampler.py#L217

**Comment by puririshi98** [comment]
cugraph issue solved: https://github.com/pyg-team/pytorch_geometric/pull/6872#discussion_r1128832879
just need to fix spmm now

**Comment by rusty1s** [comment]
Super :)

**Comment by puririshi98** [comment]
guna do a quick fix for this before looking into spmm
```
Traceback (most recent call last):
  File "argva_node_clustering.py", line 130, in <module>
    plot_points(test_data, colors)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "argva_node_clustering.py", line 121, in plot_points
    for i in range(dataset.num_classes):
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric-2.3.0-py3.8.egg/torch_geometric/data/in_memory_dataset.py", line 175, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'Planetoid' object has no attribute 'num_classes'
```

**Comment by puririshi98** [comment]
actually the spmm issue just means we need to update torch sparse :)

**Comment by puririshi98** [comment]
the reason the spmm issue occurs is that we are using torch 2.0 but likely a commit right before reduce was added as a flag to torch.sparse.mm. 
problem code: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/utils/spmm.py#L53-L64
error:
```
        # `torch.sparse.mm` only supports reductions on CPU for PyTorch>=2.0.
        # This will currently throw on error for CUDA tensors.
        if torch_geometric.typing.WITH_PT2:
            if src.layout != torch.sparse_csr:
                logging.warning("Converting sparse tensor to CSR format for more "
                                "efficient processing. Consider converting your "
                                "sparse tensor to CSR format beforehand to avoid "
                                "repeated conversion")
                src = src.to_sparse_csr()
            if reduce == 'sum':
                return torch.sparse.mm(src, other)
>           return torch.sparse.mm(src.cpu(), other.cpu(), reduce)
E           TypeError: _sparse_mm() takes 2 positional arguments but 3 were given
```
