### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by xtLyu** [pyg-team/pytorch_geometric#7951]
### 🐛 Describe the bug

from torch_geometric.datasets import Planetoid, Reddit2, Flickr, PPI, Reddit, Yelp
import torch_geometric.transforms as T
dataset = 'Flickr'
if dataset == 'Cora' or dataset == 'Citeseer' or dataset == 'Pubmed':
    datasets = Planetoid(root='./data/', name=dataset, transform=T.LargestConnectedComponents())
elif dataset == 'Flickr':
    datasets = Flickr(root='./data/Flickr/', transform=T.LargestConnectedComponents())

print(f'Dataset: {datasets}:')

Processing...
Traceback (most recent call last):
  File "aa.py", line 7, in <module>
    datasets = Flickr(root='./data/Flickr/', transform=T.LargestConnectedComponents())
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/datasets/flickr.py", line 53, in __init__
    super().__init__(root, transform, pre_transform)
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/data/dataset.py", line 230, in _process
    self.process()
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/torch_geometric/datasets/flickr.py", line 78, in process
    f = np.load(osp.join(self.raw_dir, 'adj_full.npz'))
  File "/home/lxt/anaconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

### Environment

* PyG version: 2.3.1
* PyTorch version: 2.0.1
* OS: linux
* Python version: 3.8
* CUDA/cuDNN version: 11.8
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rusty1s** [comment]
Thanks for reporting. This works fine on my end. Can you confirm that you can load the data `adj_full.npz` in a separate script (both with `allow_pickle=False/True`)?

**Comment by fishmingyu** [comment]
No I can't. Same problem for dataset Yelp.
I guess the problem is same for [issue-1](https://github.com/pyg-team/pytorch_geometric/issues/8836) and [issue-2](https://github.com/pyg-team/pytorch_geometric/issues/4911). But I still can't find the reason...
``` python
import numpy as np
np.load('data/Yelp/raw/adj_full.npz')
```

```
Traceback (most recent call last):
  File "/home/zhongming/torch_index_scatter/data/trypython.py", line 3, in <module>
    np.load('data/Yelp/raw/adj_full.npz')
  File "/home/zhongming/anaconda3/envs/torch_index/lib/python3.9/site-packages/numpy/lib/npyio.py", line 462, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```

**Comment by rusty1s** [comment]
I see. I think the google download links were recently broken in PyG due to some changes in Google Cloud. We have fixed this issue in master, so it should be already resolved if you install PyG from GitHub directly.

**Comment by fishmingyu** [comment]
Hi, thank you for your reply. However the problem remains when I locally reinstall PyG through `pip install -e .` after downloading PyG git repo. Is this the correct way of doing so?
