### ISSUE TITLE
`RuntimeError: addmm: computation on CPU is not implemented`

### ISSUE THREAD

**Issue by Charles-Ca** [pyg-team/pytorch_geometric#8977]
### 🐛 Describe the bug

Hello,

I'm quite new to Pytorch Geo, and i try toi reproduce exemple from the doc to understand
I'm trying to reproduce the following exemple : 
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/hetero/dmgi_unsup.py

At :
```python
metapaths = [
    [('movie', 'actor'), ('actor', 'movie')],
    [('movie', 'director'), ('director', 'movie')],]
data = T.AddMetaPaths(metapaths)(dataset[0])
```

I get the following error : `RuntimeError: addmm: computation on CPU is not implemented for SparseCsr + SparseCsr @ SparseCsr without MKL. PyTorch built with MKL has better support for addmm with sparse CPU tensors.`

I'm working on CPU but i'm not sure it is the issue

Thanks for you help

### Versions

torch==2.1.2
PyG==2.5.0
python==3.10.13

**Comment by rusty1s** [comment]
I somehow missed this issue, sorry. This should be resolved on latest master already.

**Comment by bryceForrest** [comment]
@rusty1s I'm using pytorch_geometric=2.5.3 and am still getting this problem, am I missing something?

**Comment by akihironitta** [comment]
@bryceForrest You might want to give it a try with `master` instead of `2.5.3`. https://github.com/pyg-team/pytorch_geometric/?tab=readme-ov-file#nightly-and-master

**Comment by joelbjervig** [comment]
Master did not solve this issue. Running Mac M1 with torch-geometric 2.6.0 from master.
